### ISSUE TITLE
Node.js 12 actions are deprecated.

### ISSUE THREAD

**Issue by cpavlatos** [iamtheyammer/branch-env-vars#16]
I am getting this warning:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: iamtheyammer/branch-env-vars.

**Comment by iamtheyammer** [comment]
I'll update the action.yml now-- it should run on node 16 with no changes

**Comment by iamtheyammer** [comment]
v1.2.1 declares node16 and [no longer has a deprecation warning](https://github.com/iamtheyammer/test-branch-env-vars/actions/runs/3364038301).
