### ISSUE TITLE
The `set-env` command is disabled starting from Nov 17 2020

### ISSUE THREAD

**Issue by gardarik** [iamtheyammer/branch-env-vars#2]
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by iamtheyammer** [comment]
All fixed in [v1.0.2](https://github.com/iamtheyammer/branch-env-vars/releases/tag/v1.0.2). Thanks for using my little action!
