### ISSUE TITLE
Variables always throwing a warning?

### ISSUE THREAD

**Issue by c-schmitz** [iamtheyammer/branch-env-vars#20]
I always get the following warning:

 Warning: Unexpected input(s) 'USER_SECRET', valid inputs are ['bevOverwrite', 'bevActionOnNoRef', 'bevSetEmptyVars']

Is that normal?
Here is the pipeline configuration:

 ```on:
  push:
    branches: 
    - stage4
    - stage
jobs:
  deploy_by_ssh_and_rsync:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.2.1
        with:
          bevSetEmptyVars: true
          USER_SECRET: |
            stage:${{ secrets.USERSTAGE }}
            stage4:${{ secrets.USERSTAGE4 }} ```

**Comment by c-schmitz** [comment]
I have no clue why Github is mangling my configuration.

**Comment by wtfzambo** [comment]
It's apparently a known issue, but it doesn't create any problem:

https://github.com/marketplace/actions/branch-based-environment-variables-that-rock#warning-unexpected-inputs-your_var_name-

**Comment by iamtheyammer** [comment]
Yes, this is expected behavior. GitHub didn’t really intend the `with` data to be used this way, but it works well and the warning is a no-op.
