### ISSUE TITLE
Node 16 is now deprecated

### ISSUE THREAD

**Issue by wardboumans** [iamtheyammer/branch-env-vars#21]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by iamtheyammer** [comment]
Hey, thanks for letting me know. I’ll update the `action.yml` file tonight. All the code is compatible with Node 20, so I won’t make any code/functionality changes.

**Comment by wardboumans** [comment]
Sweet, thanks :)
